### PR TITLE
small improvements

### PR DESCRIPTION
**Pull request by StackerDEV**
See changelog

### CODE REVIEW

**Comment by xchwarze** [comment]
Thanks for the collaboration!
to clarify some things:
1) the get_filename_from_url() helper is just to get the local download name, so you don't really have to "know" anything beyond the url
2) requests.get (url, stream = True) automatically resolves redirects so actually all sourceforge logic doesn't make sense

try this with the master code and you will see that it works perfectly 
```
[x64dbg]
folder = Dissasembler\x64dbg
url = https://sourceforge.net/projects/x64dbg/files/
update_url = https://sourceforge.net/projects/x64dbg/files/latest/download
from = web
local_version = 0
re_version = snapshot_(.*?).zip
re_download = <span class="sub-label">(.*?) \(

[AstroGrep]
folder = Other\AstroGrep
url = https://sourceforge.net/projects/astrogrep/files/
update_url = https://sourceforge.net/projects/astrogrep/files/latest/download
from = web
local_version = 0
re_version = AstroGrep_v(.*?)_portable.zip
re_download = <span class="sub-label">(.*?) \(
```

**Comment by StackerDEV** [comment]
> Thanks for the collaboration!
> to clarify some things:
> 
> 1. the get_filename_from_url() helper is just to get the local download name, so you don't really have to "know" anything beyond the url
> 2. requests.get (url, stream = True) automatically resolves redirects so actually all sourceforge logic doesn't make sense
> 
> try this with the master code and you will see that it works perfectly
> 
> ```
> [x64dbg]
> folder = Dissasembler\x64dbg
> url = https://sourceforge.net/projects/x64dbg/files/
> update_url = https://sourceforge.net/projects/x64dbg/files/latest/download
> from = web
> local_version = 0
> re_version = snapshot_(.*?).zip
> re_download = <span class="sub-label">(.*?) \(
> 
> [AstroGrep]
> folder = Other\AstroGrep
> url = https://sourceforge.net/projects/astrogrep/files/
> update_url = https://sourceforge.net/projects/astrogrep/files/latest/download
> from = web
> local_version = 0
> re_version = AstroGrep_v(.*?)_portable.zip
> re_download = <span class="sub-label">(.*?) \(
> ```
Epic fail. The clarification makes sense, strange why I didn't think of  it that way the first time. Well was fun trying to improve. I think one thing can be improved can use this to gather all information from links by using rss example "https://sourceforge.net/projects/astrogrep/rss".

**Comment by xchwarze** [comment]
very good tip that of the rss link! 

returning to the PR could accept the commits dad8ef6 and d4443d2
anyway I think that AstroGrep is not a good addition since to use the unix tools it is better to use cygwin directly and have them with the same commands and the same behavior on them

**Comment by StackerDEV** [comment]
> very good tip that of the rss link!
> 
> returning to the PR could accept the commits [dad8ef6](https://github.com/indetectables-net/toolkit/commit/dad8ef69f7cf5dfec8d8779fb45053a5471aa647) and [d4443d2](https://github.com/indetectables-net/toolkit/commit/d4443d21bafaa1714f4cca532340d119d9000414)
> anyway I think that AstroGrep is not a good addition since to use the unix tools it is better to use cygwin directly and have them with the same commands and the same behavior on them

Alright. Yeah that's also true. But idk AstroGrep can be handy for visual on windows idk I have cygwin and using it command line takes more time. I like to load classes and many different conversions for example java code in it, and search with regex for specific strings after conversion or unpack. Works really nice. By the way I still have to try APKEasyTool. I have before always used APKtool, worked great too. edit: I see that it uses APKtool but it's just a graphical interface for it, ah well. Keep my own shortcuts then.

**Comment by xchwarze** [comment]
Yes, that is a good point. Okay let's add AstroGrep

**Pull request merged**
